name: ML Workflow
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Install Packages
        run: pip install --upgrade pip && pip install -r requirements.txt
      - name: Run Data Preparation
        run: python data_preparation.py
      - name: Run Model Training
        run: python train_model.py
